x=1:100;
theta=x/10;
r=log10(x);
subplot(1,4,1);
polarplot(theta,r);%角度和半径
theta=linspace(0,2*pi);
r=cos(4*theta);
subplot(1,4,2);
polarplot(theta,r);
theta=linspace(0,2*pi,6);%间隔是5，一共六个点
r=ones(1,length(theta));
subplot(1,4,3);
polarplot(theta,r);
theta=linspace(0,2*pi);
r=1-sin(theta);
subplot(1,4,4);
polarplot(theta,r);